In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from statsmodels.multivariate.manova import MANOVA
import scipy.stats as stats

In [2]:
from pymongo import MongoClient

# Connect to MongoDB
client = MongoClient("mongodb://localhost:27017/")

# Choose your database and collection
db = client['db-untar-cafe']
students_collection = db['members']
nonCoding_collection = db['noncodingstudents']

In [3]:
# Fetch data from both collections
coding_students = list(students_collection.find({}, {"grade": 1, "science": 1, "tech": 1, "math": 1, "_id": 0}))
non_coding_students = list(nonCoding_collection.find({}, {"grade": 1, "science": 1, "tech": 1, "math": 1, "_id": 0}))


# Convert to Pandas DataFrame if needed for calculations
coding_df = pd.DataFrame(coding_students)
non_coding_df = pd.DataFrame(non_coding_students)

# Nambah data dummy untuk eksperimen
# coding_dummy = pd.DataFrame(non_coding_students)

# non_coding_dummy = pd.DataFrame(coding_students)

# coding_df = pd.concat([coding_df, coding_dummy], ignore_index=True)
# non_coding_df = pd.concat([non_coding_df, non_coding_dummy], ignore_index=True)

coding_df['group'] = 'Coding'
non_coding_df['group'] = 'NonCoding'

df = pd.concat([coding_df, non_coding_df], ignore_index=True)
df

     grade  science  tech  math      group
0        1       95    95    95     Coding
1        1       85    92    90     Coding
2        1       89    82    90     Coding
3        1       80    85    89     Coding
4        1       86    82    88     Coding
..     ...      ...   ...   ...        ...
115      6       81    81    80  NonCoding
116      6       85    85    80  NonCoding
117      6       82    80    80  NonCoding
118      6       78    74    72  NonCoding
119      6       78    78    76  NonCoding

[120 rows x 5 columns]

In [4]:
print(coding_df)

    grade  science  tech  math   group
0       1       95    95    95  Coding
1       1       85    92    90  Coding
2       1       89    82    90  Coding
3       1       80    85    89  Coding
4       1       86    82    88  Coding
5       1       89    97    78  Coding
6       1       86    85    96  Coding
7       1       78    80    82  Coding
8       2       90    95    98  Coding
9       2       90    92    90  Coding
10      2       88    82    79  Coding
11      2       91    82    82  Coding
12      2       89    79    83  Coding
13      2       83    80    88  Coding
14      2       86    94    91  Coding
15      2       81    91    84  Coding
16      3       89    87    87  Coding
17      3       89    80    87  Coding
18      3       90    92    94  Coding
19      3       80    80    80  Coding
20      3       81    92    83  Coding
21      3       85    90    85  Coding
22      3       81    88    77  Coding
23      3       87    91    92  Coding
24      3       73    86    89  Coding
25      3       80    87    84  Coding
26      3       90    98    80  Coding
27      3       87    89    89  Coding
28      4       80    93    93  Coding
29      4       87    90    90  Coding
30      4       86    90    92  Coding
31      4       85    85    84  Coding
32      4       90    90    90  Coding
33      4       93    90    94  Coding
34      4       92    92    91  Coding
35      4       85    85    90  Coding
36      4       91    81    84  Coding
37      4       77    94    81  Coding
38      4       88    87    83  Coding
39      4       81    87    85  Coding
40      4       83    87    82  Coding
41      4       84    89    83  Coding
42      4       85    90    89  Coding
43      4       92    90    86  Coding
44      4       93    97    92  Coding
45      5       80    71    71  Coding
46      5       81    89    79  Coding
47      5       84    82    74  Coding
48      5       80    90    70  Coding
49      5       81    94    85  Coding
50      5       89    87    86  Coding
51      5       92    97    87  Coding
52      5       76    82    87  Coding
53      5       87    92    79  Coding
54      6       87    84    85  Coding
55      6       85    85    74  Coding
56      6       85    89    83  Coding
57      6       86    91    87  Coding
58      6       79    84    84  Coding
59      6       95    95    91  Coding

In [5]:
print(non_coding_df)

    grade  science  tech  math      group
0       1       80    81    83  NonCoding
1       1       77    84    79  NonCoding
2       1       73    82    73  NonCoding
3       1       81    79    78  NonCoding
4       1       75    78    82  NonCoding
5       1       85    79    80  NonCoding
6       2       76    72    81  NonCoding
7       2       82    75    76  NonCoding
8       2       79    75    79  NonCoding
9       2       86    82    80  NonCoding
10      2       76    76    83  NonCoding
11      2       81    72    83  NonCoding
12      2       74    81    83  NonCoding
13      3       90    90    90  NonCoding
14      3       83    76    81  NonCoding
15      3       85    74    74  NonCoding
16      3       84    72    72  NonCoding
17      3       74    81    72  NonCoding
18      3       88    85    86  NonCoding
19      4       90    85    90  NonCoding
20      4       78    86    79  NonCoding
21      4       71    82    79  NonCoding
22      4       79    81    75  NonCoding
23      4       79    73    75  NonCoding
24      4       80    79    87  NonCoding
25      4       76    76    73  NonCoding
26      4       81    81    83  NonCoding
27      5       87    84    85  NonCoding
28      5       76    78    80  NonCoding
29      5       84    72    81  NonCoding
30      5       79    85    71  NonCoding
31      5       75    70    76  NonCoding
32      5       85    77    78  NonCoding
33      5       79    80    72  NonCoding
34      5       88    78    80  NonCoding
35      5       71    83    78  NonCoding
36      5       80    72    70  NonCoding
37      5       80    75    75  NonCoding
38      5       90    82    85  NonCoding
39      5       70    70    75  NonCoding
40      5       75    72    71  NonCoding
41      5       78    76    80  NonCoding
42      5       85    80    82  NonCoding
43      6       86    90    82  NonCoding
44      6       75    84    76  NonCoding
45      6       78    86    84  NonCoding
46      6       85    82    84  NonCoding
47      6       77    70    75  NonCoding
48      6       78    77    80  NonCoding
49      6       81    83    78  NonCoding
50      6       95    80    83  NonCoding
51      6       72    82    83  NonCoding
52      6       79    78    70  NonCoding
53      6       84    79    75  NonCoding
54      6       81    77    78  NonCoding
55      6       81    81    80  NonCoding
56      6       85    85    80  NonCoding
57      6       82    80    80  NonCoding
58      6       78    74    72  NonCoding
59      6       78    78    76  NonCoding

In [6]:
dataAsliScience = df['science']
dataAsliTech = df['tech']
dataAsliMath = df['math']

print(dataAsliScience)
print(dataAsliTech)
print(dataAsliMath)

0      95
1      85
2      89
3      80
4      86
       ..
115    81
116    85
117    82
118    78
119    78
Name: science, Length: 120, dtype: int64
0      95
1      92
2      82
3      85
4      82
       ..
115    81
116    85
117    80
118    74
119    78
Name: tech, Length: 120, dtype: int64
0      95
1      90
2      90
3      89
4      88
       ..
115    80
116    80
117    80
118    72
119    76
Name: math, Length: 120, dtype: int64

In [7]:
print('Science coding 1-3 :',coding_df[coding_df['grade'].isin([1,2,3])]['science'].mean())
print('Tech coding 1-3 :',coding_df[coding_df['grade'].isin([1,2,3])]['tech'].mean())
print('Math coding 1-3 :',coding_df[coding_df['grade'].isin([1,2,3])]['math'].mean())
print('Science non coding 1-3 :',non_coding_df[non_coding_df['grade'].isin([1,2,3])]['science'].mean())
print('Tech non coding 1-3 :',non_coding_df[non_coding_df['grade'].isin([1,2,3])]['tech'].mean())
print('Math non coding 1-3 :',non_coding_df[non_coding_df['grade'].isin([1,2,3])]['math'].mean())
print('Science coding 4-6 :',coding_df[coding_df['grade'].isin([4,5,6])]['science'].mean())
print('Tech coding 4-6 :',coding_df[coding_df['grade'].isin([4,5,6])]['tech'].mean())
print('Math coding 4-6 :',coding_df[coding_df['grade'].isin([4,5,6])]['math'].mean())
print('Science non coding 4-6 :',non_coding_df[non_coding_df['grade'].isin([4,5,6])]['science'].mean())
print('Tech non coding 4-6 :',non_coding_df[non_coding_df['grade'].isin([4,5,6])]['tech'].mean())
print('Math non coding 4-6 :',non_coding_df[non_coding_df['grade'].isin([4,5,6])]['math'].mean())

Science coding 1-3 : 85.64285714285714
Tech coding 1-3 : 87.60714285714286
Math coding 1-3 : 86.78571428571429
Science non coding 1-3 : 80.47368421052632
Tech non coding 1-3 : 78.63157894736842
Math non coding 1-3 : 79.73684210526316
Science coding 4-6 : 85.59375
Tech coding 4-6 : 88.40625
Math coding 4-6 : 84.71875
Science non coding 4-6 : 80.26829268292683
Tech non coding 4-6 : 79.09756097560975
Math non coding 4-6 : 78.4390243902439

In [8]:
grandMeanAsliS = dataAsliScience.mean()
grandMeanAsliT = dataAsliTech.mean()
grandMeanAsliM = dataAsliMath.mean()

print(grandMeanAsliS, grandMeanAsliT, grandMeanAsliM)

82.975 83.49166666666666 82.26666666666667

In [9]:
centeringDataS = dataAsliScience - grandMeanAsliS
centeringDataT = dataAsliTech - grandMeanAsliT
centeringDataM = dataAsliMath - grandMeanAsliM

print(centeringDataS)
print(centeringDataT)
print(centeringDataM)

0      12.025
1       2.025
2       6.025
3      -2.975
4       3.025
        ...
115    -1.975
116     2.025
117    -0.975
118    -4.975
119    -4.975
Name: science, Length: 120, dtype: float64
0      11.508333
1       8.508333
2      -1.491667
3       1.508333
4      -1.491667
         ...
115    -2.491667
116     1.508333
117    -3.491667
118    -9.491667
119    -5.491667
Name: tech, Length: 120, dtype: float64
0      12.733333
1       7.733333
2       7.733333
3       6.733333
4       5.733333
         ...
115    -2.266667
116    -2.266667
117    -2.266667
118   -10.266667
119    -6.266667
Name: math, Length: 120, dtype: float64

In [10]:
stdScience = dataAsliScience.std()
stdTech = dataAsliTech.std()
stdMath = dataAsliMath.std()
print(stdScience)
print(stdTech)
print(stdMath)

5.7269266693079155
6.879510234342686
6.3876631796266885

In [11]:
scalingDataS = centeringDataS / stdScience
scalingDataT = centeringDataT / stdTech
scalingDataM = centeringDataM / stdMath
print(scalingDataS)
print(scalingDataT)
print(scalingDataM)

0      2.099730
1      0.353593
2      1.052048
3     -0.519476
4      0.528207
         ...
115   -0.344862
116    0.353593
117   -0.170248
118   -0.868703
119   -0.868703
Name: science, Length: 120, dtype: float64
0      1.672842
1      1.236764
2     -0.216827
3      0.219250
4     -0.216827
         ...
115   -0.362187
116    0.219250
117   -0.507546
118   -1.379701
119   -0.798264
Name: tech, Length: 120, dtype: float64
0      1.993426
1      1.210667
2      1.210667
3      1.054115
4      0.897564
         ...
115   -0.354851
116   -0.354851
117   -0.354851
118   -1.607265
119   -0.981058
Name: math, Length: 120, dtype: float64

In [12]:
dataNewS = pd.concat([df['group'], df['grade'], scalingDataS], axis=1)
dataNewT = pd.concat([df['group'], df['grade'], scalingDataT], axis=1)
dataNewM = pd.concat([df['group'], df['grade'], scalingDataM], axis=1)

In [13]:

codingS = dataNewS[dataNewS['group'] == 'Coding']
codingT = dataNewT[dataNewT['group'] == 'Coding']
codingM = dataNewM[dataNewM['group'] == 'Coding']

print('\nCodingScience')
print(codingS)

CodingScience
     group  grade   science
0   Coding      1  2.099730
1   Coding      1  0.353593
2   Coding      1  1.052048
3   Coding      1 -0.519476
4   Coding      1  0.528207
5   Coding      1  1.052048
6   Coding      1  0.528207
7   Coding      1 -0.868703
8   Coding      2  1.226661
9   Coding      2  1.226661
10  Coding      2  0.877434
11  Coding      2  1.401275
12  Coding      2  1.052048
13  Coding      2  0.004365
14  Coding      2  0.528207
15  Coding      2 -0.344862
16  Coding      3  1.052048
17  Coding      3  1.052048
18  Coding      3  1.226661
19  Coding      3 -0.519476
20  Coding      3 -0.344862
21  Coding      3  0.353593
22  Coding      3 -0.344862
23  Coding      3  0.702820
24  Coding      3 -1.741772
25  Coding      3 -0.519476
26  Coding      3  1.226661
27  Coding      3  0.702820
28  Coding      4 -0.519476
29  Coding      4  0.702820
30  Coding      4  0.528207
31  Coding      4  0.353593
32  Coding      4  1.226661
33  Coding      4  1.750503
34  Coding      4  1.575889
35  Coding      4  0.353593
36  Coding      4  1.401275
37  Coding      4 -1.043317
38  Coding      4  0.877434
39  Coding      4 -0.344862
40  Coding      4  0.004365
41  Coding      4  0.178979
42  Coding      4  0.353593
43  Coding      4  1.575889
44  Coding      4  1.750503
45  Coding      5 -0.519476
46  Coding      5 -0.344862
47  Coding      5  0.178979
48  Coding      5 -0.519476
49  Coding      5 -0.344862
50  Coding      5  1.052048
51  Coding      5  1.575889
52  Coding      5 -1.217931
53  Coding      5  0.702820
54  Coding      6  0.702820
55  Coding      6  0.353593
56  Coding      6  0.353593
57  Coding      6  0.528207
58  Coding      6 -0.694090
59  Coding      6  2.099730

In [14]:
print('\nCodingTechnology')
print(codingT)

CodingTechnology
     group  grade      tech
0   Coding      1  1.672842
1   Coding      1  1.236764
2   Coding      1 -0.216827
3   Coding      1  0.219250
4   Coding      1 -0.216827
5   Coding      1  1.963560
6   Coding      1  0.219250
7   Coding      1 -0.507546
8   Coding      2  1.672842
9   Coding      2  1.236764
10  Coding      2 -0.216827
11  Coding      2 -0.216827
12  Coding      2 -0.652905
13  Coding      2 -0.507546
14  Coding      2  1.527483
15  Coding      2  1.091405
16  Coding      3  0.509968
17  Coding      3 -0.507546
18  Coding      3  1.236764
19  Coding      3 -0.507546
20  Coding      3  1.236764
21  Coding      3  0.946046
22  Coding      3  0.655328
23  Coding      3  1.091405
24  Coding      3  0.364609
25  Coding      3  0.509968
26  Coding      3  2.108920
27  Coding      3  0.800687
28  Coding      4  1.382124
29  Coding      4  0.946046
30  Coding      4  0.946046
31  Coding      4  0.219250
32  Coding      4  0.946046
33  Coding      4  0.946046
34  Coding      4  1.236764
35  Coding      4  0.219250
36  Coding      4 -0.362187
37  Coding      4  1.527483
38  Coding      4  0.509968
39  Coding      4  0.509968
40  Coding      4  0.509968
41  Coding      4  0.800687
42  Coding      4  0.946046
43  Coding      4  0.946046
44  Coding      4  1.963560
45  Coding      5 -1.815778
46  Coding      5  0.800687
47  Coding      5 -0.216827
48  Coding      5  0.946046
49  Coding      5  1.527483
50  Coding      5  0.509968
51  Coding      5  1.963560
52  Coding      5 -0.216827
53  Coding      5  1.236764
54  Coding      6  0.073891
55  Coding      6  0.219250
56  Coding      6  0.800687
57  Coding      6  1.091405
58  Coding      6  0.073891
59  Coding      6  1.672842

In [15]:

print('\nCodingMath')
print(codingM)

CodingMath
     group  grade      math
0   Coding      1  1.993426
1   Coding      1  1.210667
2   Coding      1  1.210667
3   Coding      1  1.054115
4   Coding      1  0.897564
5   Coding      1 -0.667954
6   Coding      1  2.149978
7   Coding      1 -0.041747
8   Coding      2  2.463081
9   Coding      2  1.210667
10  Coding      2 -0.511402
11  Coding      2 -0.041747
12  Coding      2  0.114805
13  Coding      2  0.897564
14  Coding      2  1.367219
15  Coding      2  0.271356
16  Coding      3  0.741012
17  Coding      3  0.741012
18  Coding      3  1.836874
19  Coding      3 -0.354851
20  Coding      3  0.114805
21  Coding      3  0.427908
22  Coding      3 -0.824506
23  Coding      3  1.523771
24  Coding      3  1.054115
25  Coding      3  0.271356
26  Coding      3 -0.354851
27  Coding      3  1.054115
28  Coding      4  1.680322
29  Coding      4  1.210667
30  Coding      4  1.523771
31  Coding      4  0.271356
32  Coding      4  1.210667
33  Coding      4  1.836874
34  Coding      4  1.367219
35  Coding      4  1.210667
36  Coding      4  0.271356
37  Coding      4 -0.198299
38  Coding      4  0.114805
39  Coding      4  0.427908
40  Coding      4 -0.041747
41  Coding      4  0.114805
42  Coding      4  1.054115
43  Coding      4  0.584460
44  Coding      4  1.523771
45  Coding      5 -1.763817
46  Coding      5 -0.511402
47  Coding      5 -1.294161
48  Coding      5 -1.920368
49  Coding      5  0.427908
50  Coding      5  0.584460
51  Coding      5  0.741012
52  Coding      5  0.741012
53  Coding      5 -0.511402
54  Coding      6  0.427908
55  Coding      6 -1.294161
56  Coding      6  0.114805
57  Coding      6  0.741012
58  Coding      6  0.271356
59  Coding      6  1.367219

In [16]:
nonCodingS = dataNewS[dataNewS['group'] == 'NonCoding']
nonCodingT = dataNewT[dataNewT['group'] == 'NonCoding']
nonCodingM = dataNewM[dataNewM['group'] == 'NonCoding']

print(nonCodingS)

         group  grade   science
60   NonCoding      1 -0.519476
61   NonCoding      1 -1.043317
62   NonCoding      1 -1.741772
63   NonCoding      1 -0.344862
64   NonCoding      1 -1.392544
65   NonCoding      1  0.353593
66   NonCoding      2 -1.217931
67   NonCoding      2 -0.170248
68   NonCoding      2 -0.694090
69   NonCoding      2  0.528207
70   NonCoding      2 -1.217931
71   NonCoding      2 -0.344862
72   NonCoding      2 -1.567158
73   NonCoding      3  1.226661
74   NonCoding      3  0.004365
75   NonCoding      3  0.353593
76   NonCoding      3  0.178979
77   NonCoding      3 -1.567158
78   NonCoding      3  0.877434
79   NonCoding      4  1.226661
80   NonCoding      4 -0.868703
81   NonCoding      4 -2.090999
82   NonCoding      4 -0.694090
83   NonCoding      4 -0.694090
84   NonCoding      4 -0.519476
85   NonCoding      4 -1.217931
86   NonCoding      4 -0.344862
87   NonCoding      5  0.702820
88   NonCoding      5 -1.217931
89   NonCoding      5  0.178979
90   NonCoding      5 -0.694090
91   NonCoding      5 -1.392544
92   NonCoding      5  0.353593
93   NonCoding      5 -0.694090
94   NonCoding      5  0.877434
95   NonCoding      5 -2.090999
96   NonCoding      5 -0.519476
97   NonCoding      5 -0.519476
98   NonCoding      5  1.226661
99   NonCoding      5 -2.265613
100  NonCoding      5 -1.392544
101  NonCoding      5 -0.868703
102  NonCoding      5  0.353593
103  NonCoding      6  0.528207
104  NonCoding      6 -1.392544
105  NonCoding      6 -0.868703
106  NonCoding      6  0.353593
107  NonCoding      6 -1.043317
108  NonCoding      6 -0.868703
109  NonCoding      6 -0.344862
110  NonCoding      6  2.099730
111  NonCoding      6 -1.916386
112  NonCoding      6 -0.694090
113  NonCoding      6  0.178979
114  NonCoding      6 -0.344862
115  NonCoding      6 -0.344862
116  NonCoding      6  0.353593
117  NonCoding      6 -0.170248
118  NonCoding      6 -0.868703
119  NonCoding      6 -0.868703

In [17]:
print(nonCodingT)

         group  grade      tech
60   NonCoding      1 -0.362187
61   NonCoding      1  0.073891
62   NonCoding      1 -0.216827
63   NonCoding      1 -0.652905
64   NonCoding      1 -0.798264
65   NonCoding      1 -0.652905
66   NonCoding      2 -1.670419
67   NonCoding      2 -1.234342
68   NonCoding      2 -1.234342
69   NonCoding      2 -0.216827
70   NonCoding      2 -1.088983
71   NonCoding      2 -1.670419
72   NonCoding      2 -0.362187
73   NonCoding      3  0.946046
74   NonCoding      3 -1.088983
75   NonCoding      3 -1.379701
76   NonCoding      3 -1.670419
77   NonCoding      3 -0.362187
78   NonCoding      3  0.219250
79   NonCoding      4  0.219250
80   NonCoding      4  0.364609
81   NonCoding      4 -0.216827
82   NonCoding      4 -0.362187
83   NonCoding      4 -1.525060
84   NonCoding      4 -0.652905
85   NonCoding      4 -1.088983
86   NonCoding      4 -0.362187
87   NonCoding      5  0.073891
88   NonCoding      5 -0.798264
89   NonCoding      5 -1.670419
90   NonCoding      5  0.219250
91   NonCoding      5 -1.961138
92   NonCoding      5 -0.943623
93   NonCoding      5 -0.507546
94   NonCoding      5 -0.798264
95   NonCoding      5 -0.071468
96   NonCoding      5 -1.670419
97   NonCoding      5 -1.234342
98   NonCoding      5 -0.216827
99   NonCoding      5 -1.961138
100  NonCoding      5 -1.670419
101  NonCoding      5 -1.088983
102  NonCoding      5 -0.507546
103  NonCoding      6  0.946046
104  NonCoding      6  0.073891
105  NonCoding      6  0.364609
106  NonCoding      6 -0.216827
107  NonCoding      6 -1.961138
108  NonCoding      6 -0.943623
109  NonCoding      6 -0.071468
110  NonCoding      6 -0.507546
111  NonCoding      6 -0.216827
112  NonCoding      6 -0.798264
113  NonCoding      6 -0.652905
114  NonCoding      6 -0.943623
115  NonCoding      6 -0.362187
116  NonCoding      6  0.219250
117  NonCoding      6 -0.507546
118  NonCoding      6 -1.379701
119  NonCoding      6 -0.798264

In [18]:
print(nonCodingM)

         group  grade      math
60   NonCoding      1  0.114805
61   NonCoding      1 -0.511402
62   NonCoding      1 -1.450713
63   NonCoding      1 -0.667954
64   NonCoding      1 -0.041747
65   NonCoding      1 -0.354851
66   NonCoding      2 -0.198299
67   NonCoding      2 -0.981058
68   NonCoding      2 -0.511402
69   NonCoding      2 -0.354851
70   NonCoding      2  0.114805
71   NonCoding      2  0.114805
72   NonCoding      2  0.114805
73   NonCoding      3  1.210667
74   NonCoding      3 -0.198299
75   NonCoding      3 -1.294161
76   NonCoding      3 -1.607265
77   NonCoding      3 -1.607265
78   NonCoding      3  0.584460
79   NonCoding      4  1.210667
80   NonCoding      4 -0.511402
81   NonCoding      4 -0.511402
82   NonCoding      4 -1.137610
83   NonCoding      4 -1.137610
84   NonCoding      4  0.741012
85   NonCoding      4 -1.450713
86   NonCoding      4  0.114805
87   NonCoding      5  0.427908
88   NonCoding      5 -0.354851
89   NonCoding      5 -0.198299
90   NonCoding      5 -1.763817
91   NonCoding      5 -0.981058
92   NonCoding      5 -0.667954
93   NonCoding      5 -1.607265
94   NonCoding      5 -0.354851
95   NonCoding      5 -0.667954
96   NonCoding      5 -1.920368
97   NonCoding      5 -1.137610
98   NonCoding      5  0.427908
99   NonCoding      5 -1.137610
100  NonCoding      5 -1.763817
101  NonCoding      5 -0.354851
102  NonCoding      5 -0.041747
103  NonCoding      6 -0.041747
104  NonCoding      6 -0.981058
105  NonCoding      6  0.271356
106  NonCoding      6  0.271356
107  NonCoding      6 -1.137610
108  NonCoding      6 -0.354851
109  NonCoding      6 -0.667954
110  NonCoding      6  0.114805
111  NonCoding      6  0.114805
112  NonCoding      6 -1.920368
113  NonCoding      6 -1.137610
114  NonCoding      6 -0.667954
115  NonCoding      6 -0.354851
116  NonCoding      6 -0.354851
117  NonCoding      6 -0.354851
118  NonCoding      6 -1.607265
119  NonCoding      6 -0.981058

In [19]:
codingS['science'].mean()

0.4612712575532088

In [20]:
grandMeanS = (round(codingS['science'].mean(),2) + round(nonCodingS['science'].mean(),2)) / 2
grandMeanT = (round(codingT['tech'].mean(),2) + round(nonCodingT['tech'].mean(),2)) / 2
grandMeanM = (round(codingM['math'].mean(),2) + round(nonCodingM['math'].mean(),2)) / 2

grandMean = [grandMeanS, grandMeanT, grandMeanM]
grandMean = np.matrix(grandMean)
grandMean

# grandMeanS = 0
# grandMeanT = 0
# grandMeanM = 0

grandMean = [grandMeanS, grandMeanT, grandMeanM]
grandMean = np.matrix(grandMean)
grandMean

matrix([[0., 0., 0.]])

In [21]:
I = 2 # total group (coding dan non coding)
J = 2 # total group (kelas 1-3 dan kelas 4-6)
K = len(dataAsliMath) # total data
d = 3 # total variable independent
mE = I*J*(K - 1) # degrees of freedom error
v1 = d
v2 = mE + 1 - d
print(K)
print(mE)

120
476

In [22]:
ySC = codingS['science'].mean()
yTC = codingT['tech'].mean()
yMC = codingM['math'].mean()
yiCoding = [ySC, yTC, yMC]
yiCoding = np.matrix(yiCoding)
print(yiCoding)
y1 = yiCoding - grandMean
y1T = y1.T
print(y1T)
SSA1 = J * np.dot(y1T, y1)
SSA1

[[0.46127126 0.66017296 0.53488523]]
[[0.46127126]
 [0.66017296]
 [0.53488523]]

matrix([[0.42554235, 0.60903763, 0.49345436],
        [0.60903763, 0.87165669, 0.70623353],
        [0.49345436, 0.70623353, 0.57220441]])

In [23]:
ySnC = nonCodingS['science'].mean()
yTnC = nonCodingT['tech'].mean()
yMnC = nonCodingM['math'].mean()
yinonCoding = [ySnC, yTnC, yMnC]
yinonCoding = np.array(yinonCoding)
print(yinonCoding)
y2 = yinonCoding - grandMean
y2
y2T = y2.T
print(y2.T)
SSA2 = J * np.dot(y2T, y2)
SSA2

[-0.46127126 -0.66017296 -0.53488523]
[[-0.46127126]
 [-0.66017296]
 [-0.53488523]]

matrix([[0.42554235, 0.60903763, 0.49345436],
        [0.60903763, 0.87165669, 0.70623353],
        [0.49345436, 0.70623353, 0.57220441]])

In [24]:
factorA = np.round(SSA1 + SSA2, decimals=6)
# factorA = factorA * 2 * len(dataAsliMath)
factorA

array([[0.851085, 1.218075, 0.986909],
       [1.218075, 1.743313, 1.412467],
       [0.986909, 1.412467, 1.144409]])

In [25]:
dataScience13 = codingS[codingS['grade'].isin([1,2,3])]
dataTech13 = codingT[codingT['grade'].isin([1,2,3])]
dataMath13 = codingM[codingM['grade'].isin([1,2,3])]

dataScience13 = dataScience13.drop(['group', 'grade'], axis=1)
dataTech13 = dataTech13.drop(['group', 'grade'], axis=1)
dataMath13 = dataMath13.drop(['group', 'grade'], axis=1)

In [26]:
yijcS13 = dataScience13.mean()
yijcT13 = dataTech13.mean()
yijcM13 = dataMath13.mean()
yijCoding13 = np.matrix([yijcS13,yijcT13,yijcM13])
yijCoding13

matrix([[0.46584447],
        [0.59822226],
        [0.70746492]])

In [27]:
nondataScience13 = nonCodingS[nonCodingS['grade'].isin([1,2,3])]
nondataTech13 = nonCodingT[nonCodingT['grade'].isin([1,2,3])]
nondataMath13 = nonCodingM[nonCodingM['grade'].isin([1,2,3])]

nondataScience13 = nondataScience13.drop(['group', 'grade'], axis=1)
nondataTech13 = nondataTech13.drop(['group', 'grade'], axis=1)
nondataMath13 = nondataMath13.drop(['group', 'grade'], axis=1)

In [28]:
yijnS13 = nondataScience13.mean()
yijnT13 = nondataTech13.mean()
yijnM13 = nondataMath13.mean()
yijnonCoding13 = np.matrix([yijnS13,yijnT13,yijnM13])
yijnonCoding13

matrix([[-0.43676407],
        [-0.70645839],
        [-0.39604852]])

In [29]:
dataScience46 = codingS[codingS['grade'].isin([4,5,6])]
dataTech46 = codingT[codingT['grade'].isin([4,5,6])]
dataMath46 = codingM[codingM['grade'].isin([4,5,6])]

dataScience46 = dataScience46.drop(['group', 'grade'], axis=1)
dataTech46 = dataTech46.drop(['group', 'grade'], axis=1)
dataMath46 = dataMath46.drop(['group', 'grade'], axis=1)

In [30]:
yijcS46 = dataScience46.mean()
yijcT46 = dataTech46.mean()
yijcM46 = dataMath46.mean()
yijCoding46 = np.matrix([yijcS46,yijcT46,yijcM46])
yijCoding46

matrix([[0.45726969],
        [0.71437983],
        [0.38387799]])

In [31]:
nondataScience46 = nonCodingS[nonCodingS['grade'].isin([4,5,6])]
nondataTech46 = nonCodingT[nonCodingT['grade'].isin([4,5,6])]
nondataMath46 = nonCodingM[nonCodingM['grade'].isin([4,5,6])]

nondataScience46 = nondataScience46.drop(['group', 'grade'], axis=1)
nondataTech46 = nondataTech46.drop(['group', 'grade'], axis=1)
nondataMath46 = nondataMath46.drop(['group', 'grade'], axis=1)

In [32]:
yijnS46 = nondataScience46.mean()
yijnT46 = nondataTech46.mean()
yijnM46 = nondataMath46.mean()
yijnonCoding46 = np.matrix([yijnS46,yijnT46,yijnM46])
yijnonCoding46

matrix([[-0.47262825],
        [-0.63872362],
        [-0.59922419]])

In [33]:
meanyjS13 = np.concatenate([np.ravel(dataScience13), np.ravel(nondataScience13)])
meanyjT13 = np.concatenate([np.ravel(dataTech13), np.ravel(nondataTech13)])
meanyjM13 = np.concatenate([np.ravel(dataMath13), np.ravel(nondataMath13)])
yjS13 = meanyjS13.mean()
yjT13 = meanyjT13.mean()
yjM13 = meanyjM13.mean()
yj13 = np.matrix([yjS13, yjT13, yjM13])
yj13

matrix([[0.10096017, 0.07079817, 0.26136374]])

In [34]:
meanyjS46 = np.concatenate([np.ravel(dataScience46), np.ravel(nondataScience46)])
meanyjT46 = np.concatenate([np.ravel(dataTech46), np.ravel(nondataTech46)])
meanyjM46 = np.concatenate([np.ravel(dataMath46), np.ravel(nondataMath46)])
yjS46 = meanyjS46.mean()
yjT46 = meanyjT46.mean()
yjM46 = meanyjM46.mean()
yj46 = np.matrix([yjS46, yjT46, yjM46])
yj46

matrix([[-0.06500175, -0.04558238, -0.16827529]])

In [35]:
yj1 = yj13 - grandMean
SSB1 = I *  np.dot(yj1.T, yj1)
print(SSB1)
yj2 = yj46 - grandMean
SSB2 = I * np.dot(yj2.T, yj2)
print(SSB2)
factorB = np.round(SSB1 + SSB2, decimals=6)
factorB

[[0.02038591 0.01429559 0.05277466]
 [0.01429559 0.01002476 0.03700815]
 [0.05277466 0.03700815 0.13662201]]
[[0.00845046 0.00592587 0.02187638]
 [0.00592587 0.00415551 0.01534078]
 [0.02187638 0.01534078 0.05663314]]

array([[0.028836, 0.020221, 0.074651],
       [0.020221, 0.01418 , 0.052349],
       [0.074651, 0.052349, 0.193255]])

In [36]:
h31 = yijCoding13 - yiCoding - yj13 + grandMean
H31 =  np.dot(h31.T, h31)

h32 = yijnonCoding13 - yinonCoding - yj13 + grandMean
H32 =  np.dot(h32.T, h32)

h33 = yijCoding46 - yiCoding - yj46 + grandMean
H33 =  np.dot(h33.T, h33)

h34 = yijnonCoding46 - yinonCoding - yj46 + grandMean
H34 =  np.dot(h34.T, h34)

factorAB = H31 + H32 + H33 + H34
# H3 = 20 * H3
factorAB

matrix([[0.28453225, 0.06151774, 0.29202832],
        [0.06151774, 0.32096704, 0.20365554],
        [0.29202832, 0.20365554, 0.58292096]])

In [37]:
dataCoding13 = pd.concat([dataScience13, dataTech13, dataMath13], axis=1)
dataCoding46 = pd.concat([dataScience46, dataTech46, dataMath46], axis=1)
nondataCoding13 = pd.concat([nondataScience13, nondataTech13, nondataMath13], axis=1)
nondataCoding46 = pd.concat([nondataScience46, nondataTech46, nondataMath46], axis=1)
dataCoding13

     science      tech      math
0   2.099730  1.672842  1.993426
1   0.353593  1.236764  1.210667
2   1.052048 -0.216827  1.210667
3  -0.519476  0.219250  1.054115
4   0.528207 -0.216827  0.897564
5   1.052048  1.963560 -0.667954
6   0.528207  0.219250  2.149978
7  -0.868703 -0.507546 -0.041747
8   1.226661  1.672842  2.463081
9   1.226661  1.236764  1.210667
10  0.877434 -0.216827 -0.511402
11  1.401275 -0.216827 -0.041747
12  1.052048 -0.652905  0.114805
13  0.004365 -0.507546  0.897564
14  0.528207  1.527483  1.367219
15 -0.344862  1.091405  0.271356
16  1.052048  0.509968  0.741012
17  1.052048 -0.507546  0.741012
18  1.226661  1.236764  1.836874
19 -0.519476 -0.507546 -0.354851
20 -0.344862  1.236764  0.114805
21  0.353593  0.946046  0.427908
22 -0.344862  0.655328 -0.824506
23  0.702820  1.091405  1.523771
24 -1.741772  0.364609  1.054115
25 -0.519476  0.509968  0.271356
26  1.226661  2.108920 -0.354851
27  0.702820  0.800687  1.054115

In [38]:
yijCoding13 = np.array(yijCoding13.T)
yijCoding46 = np.array(yijCoding46.T)
yijnonCoding13 = np.array(yijnonCoding13.T)
yijnonCoding46 = np.array(yijnonCoding46.T)

In [39]:
errordataCoding13 = dataCoding13 - yijCoding13
errordataCoding13

     science      tech      math
0   1.633886  1.074620  1.285961
1  -0.112252  0.638542  0.503202
2   0.586203 -0.815050  0.503202
3  -0.985320 -0.378972  0.346650
4   0.062362 -0.815050  0.190099
5   0.586203  1.365338 -1.375419
6   0.062362 -0.378972  1.442513
7  -1.334548 -1.105768 -0.749212
8   0.760817  1.074620  1.755616
9   0.760817  0.638542  0.503202
10  0.411589 -0.815050 -1.218867
11  0.935431 -0.815050 -0.749212
12  0.586203 -1.251127 -0.592660
13 -0.461479 -1.105768  0.190099
14  0.062362  0.929261  0.659754
15 -0.810707  0.493183 -0.436109
16  0.586203 -0.088254  0.033547
17  0.586203 -1.105768  0.033547
18  0.760817  0.638542  1.129409
19 -0.985320 -1.105768 -1.062316
20 -0.810707  0.638542 -0.592660
21 -0.112252  0.347824 -0.279557
22 -0.810707  0.057105 -1.531971
23  0.236976  0.493183  0.816306
24 -2.207616 -0.233613  0.346650
25 -0.985320 -0.088254 -0.436109
26  0.760817  1.510697 -1.062316
27  0.236976  0.202465  0.346650

In [40]:
errordataCoding46 = dataCoding46 - yijCoding46
errordataCoding46

     science      tech      math
28 -0.976746  0.667744  1.296444
29  0.245551  0.231666  0.826789
30  0.070937  0.231666  1.139893
31 -0.103677 -0.495130 -0.112522
32  0.769392  0.231666  0.826789
33  1.293233  0.231666  1.452996
34  1.118619  0.522385  0.983341
35 -0.103677 -0.495130  0.826789
36  0.944005 -1.076566 -0.112522
37 -1.500587  0.813103 -0.582177
38  0.420164 -0.204411 -0.269073
39 -0.802132 -0.204411  0.044030
40 -0.452904 -0.204411 -0.425625
41 -0.278291  0.086307 -0.269073
42 -0.103677  0.231666  0.670237
43  1.118619  0.231666  0.200582
44  1.293233  1.249180  1.139893
45 -0.976746 -2.530158 -2.147695
46 -0.802132  0.086307 -0.895280
47 -0.278291 -0.931207 -1.678039
48 -0.976746  0.231666 -2.304246
49 -0.802132  0.813103  0.044030
50  0.594778 -0.204411  0.200582
51  1.118619  1.249180  0.357134
52 -1.675200 -0.931207  0.357134
53  0.245551  0.522385 -0.895280
54  0.245551 -0.640489  0.044030
55 -0.103677 -0.495130 -1.678039
56 -0.103677  0.086307 -0.269073
57  0.070937  0.377025  0.357134
58 -1.151359 -0.640489 -0.112522
59  1.642460  0.958462  0.983341

In [41]:
errornondataCoding13 = nondataCoding13 - yijnonCoding13
errornondataCoding13

     science      tech      math
60 -0.082712  0.344272  0.510853
61 -0.606553  0.780349 -0.115354
62 -1.305008  0.489631 -1.054665
63  0.091902  0.053553 -0.271906
64 -0.955780 -0.091806  0.354301
65  0.790357  0.053553  0.041198
66 -0.781167 -0.963961  0.197750
67  0.266516 -0.527883 -0.585009
68 -0.257325 -0.527883 -0.115354
69  0.964971  0.489631  0.041198
70 -0.781167 -0.382524  0.510853
71  0.091902 -0.963961  0.510853
72 -1.130394  0.344272  0.510853
73  1.663425  1.652504  1.606716
74  0.441129 -0.382524  0.197750
75  0.790357 -0.673243 -0.898113
76  0.615743 -0.963961 -1.211216
77 -1.130394  0.344272 -1.211216
78  1.314198  0.925708  0.980508

In [42]:
errornondataCoding46 = nondataCoding46 - yijnonCoding46
errornondataCoding46

      science      tech      math
79   1.699290  0.857974  1.809891
80  -0.396075  1.003333  0.087822
81  -1.618371  0.421896  0.087822
82  -0.221461  0.276537 -0.538385
83  -0.221461 -0.886336 -0.538385
84  -0.046848 -0.014181  1.340236
85  -0.745302 -0.450259 -0.851489
86   0.127766  0.276537  0.714029
87   1.175448  0.712615  1.027132
88  -0.745302 -0.159541  0.244374
89   0.651607 -1.031696  0.400925
90  -0.221461  0.857974 -1.164592
91  -0.919916 -1.322414 -0.381834
92   0.826221 -0.304900 -0.068730
93  -0.221461  0.131178 -1.008041
94   1.350062 -0.159541  0.244374
95  -1.618371  0.567255 -0.068730
96  -0.046848 -1.031696 -1.321144
97  -0.046848 -0.595618 -0.538385
98   1.699290  0.421896  1.027132
99  -1.792985 -1.322414 -0.538385
100 -0.919916 -1.031696 -1.164592
101 -0.396075 -0.450259  0.244374
102  0.826221  0.131178  0.557477
103  1.000835  1.584770  0.557477
104 -0.919916  0.712615 -0.381834
105 -0.396075  1.003333  0.870581
106  0.826221  0.421896  0.870581
107 -0.570689 -1.322414 -0.538385
108 -0.396075 -0.304900  0.244374
109  0.127766  0.567255 -0.068730
110  2.572358  0.131178  0.714029
111 -1.443757  0.421896  0.714029
112 -0.221461 -0.159541 -1.321144
113  0.651607 -0.014181 -0.538385
114  0.127766 -0.304900 -0.068730
115  0.127766  0.276537  0.244374
116  0.826221  0.857974  0.244374
117  0.302380  0.131178  0.244374
118 -0.396075 -0.740977 -1.008041
119 -0.396075 -0.159541 -0.381834

In [43]:
errorCoding13 = []
errordataCoding13 = np.matrix(errordataCoding13)
for i in range(errordataCoding13.shape[0]):
    result = np.dot(errordataCoding13[i].T, errordataCoding13[i])
    errorCoding13.append(result)   
    
hasilCoding13 = sum(errorCoding13)
print("sum :\n", hasilCoding13)
print(f"\nRow multiplication result:")
print(errorCoding13)

sum :
 [[19.64859689  5.61117062  5.59999296]
 [ 5.61117062 19.07295968  4.27004555]
 [ 5.59999296  4.27004555 20.65362753]]

Row multiplication result:
[matrix([[2.66958206, 1.7558056 , 2.10111312],
        [1.7558056 , 1.15480747, 1.38191901],
        [2.10111312, 1.38191901, 1.65369569]]), matrix([[ 0.01260044, -0.07167743, -0.05648528],
        [-0.07167743,  0.40773606,  0.32131576],
        [-0.05648528,  0.32131576,  0.25321238]]), matrix([[ 0.34363422, -0.47778477,  0.29497871],
        [-0.47778477,  0.66430604, -0.41013475],
        [ 0.29497871, -0.41013475,  0.25321238]]), matrix([[ 0.97085611,  0.37340897, -0.34156163],
        [ 0.37340897,  0.1436199 , -0.13137083],
        [-0.34156163, -0.13137083,  0.12016647]]), matrix([[ 0.00388902, -0.05082817,  0.01185494],
        [-0.05082817,  0.66430604, -0.1549398 ],
        [ 0.01185494, -0.1549398 ,  0.03613747]]), matrix([[ 0.34363422,  0.80036557, -0.80627514],
        [ 0.80036557,  1.86414801, -1.87791212],
        [-0.80627514, -1.87791212,  1.89177785]]), matrix([[ 0.00388902, -0.02363348,  0.08995805],
        [-0.02363348,  0.1436199 , -0.54667218],
        [ 0.08995805, -0.54667218,  2.08084309]]), matrix([[1.78101772, 1.47570032, 0.99985927],
        [1.47570032, 1.22272306, 0.82845478],
        [0.99985927, 0.82845478, 0.56131871]]), matrix([[0.57884242, 0.81758887, 1.33570265],
        [0.81758887, 1.15480747, 1.88661986],
        [1.33570265, 1.88661986, 3.08218866]]), matrix([[0.57884242, 0.48581368, 0.38284471],
        [0.48581368, 0.40773606, 0.32131576],
        [0.38284471, 0.32131576, 0.25321238]]), matrix([[ 0.16940591, -0.3354659 , -0.50167301],
        [-0.3354659 ,  0.66430604,  0.99343751],
        [-0.50167301,  0.99343751,  1.48563769]]), matrix([[ 0.87503054, -0.7624225 , -0.70083594],
        [-0.7624225 ,  0.66430604,  0.61064508],
        [-0.70083594,  0.61064508,  0.56131871]]), matrix([[ 0.34363422, -0.73341483, -0.34741937],
        [-0.73341483,  1.56531945,  0.74149345],
        [-0.34741937,  0.74149345,  0.35124621]]), matrix([[ 0.21296299,  0.51028889, -0.08772653],
        [ 0.51028889,  1.22272306, -0.21020495],
        [-0.08772653, -0.21020495,  0.03613747]]), matrix([[0.00388902, 0.05795059, 0.0411436 ],
        [0.05795059, 0.86352508, 0.61308324],
        [0.0411436 , 0.61308324, 0.43527521]]), matrix([[ 0.65724516, -0.39982666,  0.35355604],
        [-0.39982666,  0.24322942, -0.21508128],
        [ 0.35355604, -0.21508128,  0.19019063]]), matrix([[ 0.34363422, -0.05173466,  0.01966525],
        [-0.05173466,  0.00778873, -0.00296063],
        [ 0.01966525, -0.00296063,  0.00112539]]), matrix([[ 3.43634216e-01, -6.48204813e-01,  1.96652473e-02],
        [-6.48204813e-01,  1.22272306e+00, -3.70949903e-02],
        [ 1.96652473e-02, -3.70949903e-02,  1.12538837e-03]]), matrix([[0.57884242, 0.48581368, 0.85927368],
        [0.48581368, 0.40773606, 0.72117538],
        [0.85927368, 0.72117538, 1.2755652 ]]), matrix([[0.97085611, 1.08953575, 1.04672114],
        [1.08953575, 1.22272306, 1.17467469],
        [1.04672114, 1.17467469, 1.12851445]]), matrix([[ 0.65724516, -0.51767031,  0.48047359],
        [-0.51767031,  0.40773606, -0.37843856],
        [ 0.48047359, -0.37843856,  0.35124621]]), matrix([[ 0.01260044, -0.0390438 ,  0.03138071],
        [-0.0390438 ,  0.12098137, -0.09723648],
        [ 0.03138071, -0.09723648,  0.07815197]]), matrix([[ 0.65724516, -0.04629572,  1.24197891],
        [-0.04629572,  0.00326103, -0.0874838 ],
        [ 1.24197891, -0.0874838 ,  2.34693492]]), matrix([[0.05615752, 0.11687241, 0.19344467],
        [0.11687241, 0.24322942, 0.40258804],
        [0.19344467, 0.40258804, 0.66635496]]), matrix([[ 4.8735701 ,  0.51572783, -0.765271  ],
        [ 0.51572783,  0.05457502, -0.08098202],
        [-0.765271  , -0.08098202,  0.12016647]]), matrix([[0.97085611, 0.08695825, 0.42970657],
        [0.08695825, 0.00778873, 0.03848823],
        [0.42970657, 0.03848823, 0.19019063]]), matrix([[ 0.57884242,  1.14936406, -0.80822772],
        [ 1.14936406,  2.28220616, -1.60483726],
        [-0.80822772, -1.60483726,  1.12851445]]), matrix([[0.05615752, 0.0479792 , 0.08214773],
        [0.0479792 , 0.04099191, 0.07018442],
        [0.08214773, 0.07018442, 0.12016647]])]

In [44]:
errorCoding46 = []
errordataCoding46 = np.matrix(errordataCoding46)
for i in range(errordataCoding46.shape[0]):
    result = np.dot(errordataCoding46[i].T, errordataCoding46[i])
    errorCoding46.append(result)   
    
hasilCoding46 = sum(errorCoding46)
print("sum :\n", hasilCoding46)
print(f"\nRow multiplication result:")
print(errorCoding46)

sum :
 [[23.59064836  7.31707073 12.25596438]
 [ 7.31707073 17.91169753 11.34754041]
 [12.25596438 11.34754041 29.22557006]]

Row multiplication result:
[matrix([[ 0.95403182, -0.65221573, -1.26629624],
        [-0.65221573,  0.44588172,  0.86569264],
        [-1.26629624,  0.86569264,  1.68076802]]), matrix([[0.06029507, 0.05688576, 0.20301851],
        [0.05688576, 0.05366923, 0.19153908],
        [0.20301851, 0.19153908, 0.68358014]]), matrix([[0.00503203, 0.01643366, 0.08086036],
        [0.01643366, 0.05366923, 0.26407459],
        [0.08086036, 0.26407459, 1.29935514]]), matrix([[0.0107489 , 0.05133351, 0.01166589],
        [0.05133351, 0.24515344, 0.05571278],
        [0.01166589, 0.05571278, 0.01266111]]), matrix([[0.59196363, 0.17824206, 0.63612466],
        [0.17824206, 0.05366923, 0.19153908],
        [0.63612466, 0.19153908, 0.68358014]]), matrix([[1.67245134, 0.29959835, 1.87906243],
        [0.29959835, 0.05366923, 0.3366101 ],
        [1.87906243, 0.3366101 , 2.11119781]]), matrix([[1.25130886, 0.5843494 , 1.09998391],
        [0.5843494 , 0.27288564, 0.51368208],
        [1.09998391, 0.51368208, 0.96695918]]), matrix([[ 0.0107489 ,  0.05133351, -0.08571893],
        [ 0.05133351,  0.24515344, -0.40936784],
        [-0.08571893, -0.40936784,  0.68358014]]), matrix([[ 0.89114629, -1.01628461, -0.10622099],
        [-1.01628461,  1.15899535,  0.12113697],
        [-0.10622099,  0.12113697,  0.01266111]]), matrix([[ 2.25176045, -1.22013146,  0.87360693],
        [-1.22013146,  0.66113639, -0.47336976],
        [ 0.87360693, -0.47336976,  0.33892995]]), matrix([[ 0.17653802, -0.08588635, -0.11305501],
        [-0.08588635,  0.041784  ,  0.05500165],
        [-0.11305501,  0.05500165,  0.07240047]]), matrix([[ 0.64341543,  0.16396485, -0.03531801],
        [ 0.16396485,  0.041784  , -0.00900027],
        [-0.03531801, -0.00900027,  0.00193866]]), matrix([[0.20512235, 0.09257879, 0.19276747],
        [0.09257879, 0.041784  , 0.08700261],
        [0.19276747, 0.08700261, 0.18115676]]), matrix([[ 0.07744567, -0.02401843,  0.07488059],
        [-0.02401843,  0.0074489 , -0.02322292],
        [ 0.07488059, -0.02322292,  0.07240047]]), matrix([[ 0.0107489 , -0.02401843, -0.06948812],
        [-0.02401843,  0.05366923,  0.15527132],
        [-0.06948812,  0.15527132,  0.44921801]]), matrix([[1.25130886, 0.25914626, 0.22437483],
        [0.25914626, 0.05366923, 0.04646806],
        [0.22437483, 0.04646806, 0.04023312]]), matrix([[1.67245134, 1.61548132, 1.47414662],
        [1.61548132, 1.56045191, 1.4239316 ],
        [1.47414662, 1.4239316 , 1.29935514]]), matrix([[0.95403182, 2.47132081, 2.09775113],
        [2.47132081, 6.40170108, 5.43400746],
        [2.09775113, 5.43400746, 4.61259228]]), matrix([[ 0.64341543, -0.0692296 ,  0.71813292],
        [-0.0692296 ,  0.0074489 , -0.07726898],
        [ 0.71813292, -0.07726898,  0.80152709]]), matrix([[0.07744567, 0.25914626, 0.46698261],
        [0.25914626, 0.86714699, 1.56260243],
        [0.46698261, 1.56260243, 2.81581597]]), matrix([[ 0.95403182, -0.22627893,  2.25066238],
        [-0.22627893,  0.05366923, -0.53381601],
        [ 2.25066238, -0.53381601,  5.30955155]]), matrix([[ 0.64341543, -0.65221573, -0.03531801],
        [-0.65221573,  0.66113639,  0.03580107],
        [-0.03531801,  0.03580107,  0.00193866]]), matrix([[ 0.35376087, -0.12157938,  0.11930174],
        [-0.12157938,  0.041784  , -0.04100123],
        [ 0.11930174, -0.04100123,  0.04023312]]), matrix([[1.25130886, 1.39735726, 0.39949664],
        [1.39735726, 1.56045191, 0.44612449],
        [0.39949664, 0.44612449, 0.1275445 ]]), matrix([[ 2.80629647,  1.55995883, -0.59827058],
        [ 1.55995883,  0.86714699, -0.33256553],
        [-0.59827058, -0.33256553,  0.1275445 ]]), matrix([[ 0.06029507,  0.12827182, -0.21983661],
        [ 0.12827182,  0.27288564, -0.4676807 ],
        [-0.21983661, -0.4676807 ,  0.80152709]]), matrix([[ 0.06029507, -0.1572724 ,  0.01081164],
        [-0.1572724 ,  0.41022604, -0.02820085],
        [ 0.01081164, -0.02820085,  0.00193866]]), matrix([[0.0107489 , 0.05133351, 0.17397391],
        [0.05133351, 0.24515344, 0.83084715],
        [0.17397391, 0.83084715, 2.81581597]]), matrix([[ 0.0107489 , -0.00894804,  0.02789669],
        [-0.00894804,  0.0074489 , -0.02322292],
        [ 0.02789669, -0.02322292,  0.07240047]]), matrix([[0.00503203, 0.02674498, 0.02533393],
        [0.02674498, 0.14214814, 0.13464848],
        [0.02533393, 0.13464848, 0.1275445 ]]), matrix([[1.32562812, 0.73743283, 0.12955277],
        [0.73743283, 0.41022604, 0.07206883],
        [0.12955277, 0.07206883, 0.01266111]]), matrix([[2.69767601, 1.57423604, 1.61509832],
        [1.57423604, 0.91864965, 0.94249494],
        [1.61509832, 0.94249494, 0.96695918]])]

In [45]:
errornonCoding13 = []
errornondataCoding13 = np.matrix(errornondataCoding13)
for i in range(errornondataCoding13.shape[0]):
    result = np.dot(errornondataCoding13[i].T, errornondataCoding13[i])
    errornonCoding13.append(result)   
    
hasilnonCoding13 = sum(errornonCoding13)
print("sum :\n", hasilnonCoding13)
print(f"\nRow multiplication result:")
print(errornonCoding13)

sum :
 [[14.1698045   2.31775077  3.86445965]
 [ 2.31775077  9.13675096  4.05420349]
 [ 3.86445965  4.05420349 10.08974511]]

Row multiplication result:
[matrix([[ 0.00684124, -0.02847532, -0.04225357],
        [-0.02847532,  0.11852304,  0.17587231],
        [-0.04225357,  0.17587231,  0.26097095]]), matrix([[ 0.36790647, -0.47332317,  0.06996827],
        [-0.47332317,  0.60894504, -0.09001637],
        [ 0.06996827, -0.09001637,  0.01330653]]), matrix([[ 1.70304547, -0.63897221,  1.37634555],
        [-0.63897221,  0.23973846, -0.51639641],
        [ 1.37634555, -0.51639641,  1.11231738]]), matrix([[ 0.00844597,  0.00492166, -0.02498867],
        [ 0.00492166,  0.00286796, -0.01456147],
        [-0.02498867, -0.01456147,  0.07393272]]), matrix([[ 0.91351616,  0.08774618, -0.33863431],
        [ 0.08774618,  0.00842831, -0.03252692],
        [-0.33863431, -0.03252692,  0.12552947]]), matrix([[0.62466397, 0.04232628, 0.03256099],
        [0.04232628, 0.00286796, 0.00220628],
        [0.03256099, 0.00220628, 0.00169726]]), matrix([[ 0.61022136,  0.75301413, -0.1544754 ],
        [ 0.75301413,  0.92922064, -0.19062289],
        [-0.1544754 , -0.19062289,  0.03910491]]), matrix([[ 0.07103061, -0.14068919, -0.15591414],
        [-0.14068919,  0.27866084,  0.30881665],
        [-0.15591414,  0.30881665,  0.34223583]]), matrix([[0.06621641, 0.13583784, 0.02968351],
        [0.13583784, 0.27866084, 0.06089342],
        [0.02968351, 0.06089342, 0.01330653]]), matrix([[0.93116823, 0.47247945, 0.0397547 ],
        [0.47247945, 0.23973846, 0.02017173],
        [0.0397547 , 0.02017173, 0.00169726]]), matrix([[ 0.61022136,  0.29881513, -0.39906146],
        [ 0.29881513,  0.14632474, -0.19541368],
        [-0.39906146, -0.19541368,  0.26097095]]), matrix([[ 0.00844597, -0.0885899 ,  0.04694841],
        [-0.0885899 ,  0.92922064, -0.49244247],
        [ 0.04694841, -0.49244247,  0.26097095]]), matrix([[ 1.27779086, -0.38916276, -0.5774654 ],
        [-0.38916276,  0.11852304,  0.17587231],
        [-0.5774654 ,  0.17587231,  0.26097095]]), matrix([[2.76698435, 2.74881797, 2.67265163],
        [2.74881797, 2.73077085, 2.65510458],
        [2.67265163, 2.65510458, 2.58153493]]), matrix([[ 0.19459516, -0.16874266,  0.08723317],
        [-0.16874266,  0.14632474, -0.07564401],
        [ 0.08723317, -0.07564401,  0.03910491]]), matrix([[ 0.62466397, -0.53210186, -0.70982962],
        [-0.53210186,  0.45325552,  0.60464775],
        [-0.70982962,  0.60464775,  0.80660661]]), matrix([[ 0.37913961, -0.59355231, -0.74579816],
        [-0.59355231,  0.92922064,  1.16756522],
        [-0.74579816,  1.16756522,  1.46704506]]), matrix([[ 1.27779086, -0.38916276,  1.36915184],
        [-0.38916276,  0.11852304, -0.41698758],
        [ 1.36915184, -0.41698758,  1.46704506]]), matrix([[1.72711648, 1.21656428, 1.28858232],
        [1.21656428, 0.85693621, 0.90766502],
        [1.28858232, 0.90766502, 0.96139687]])]

In [46]:
errornonCoding46 = []
errornondataCoding46 = np.matrix(errornondataCoding46)
for i in range(errornondataCoding46.shape[0]):
    result = np.dot(errornondataCoding46[i].T, errornondataCoding46[i])
    errornonCoding46.append(result)   
    
hasilnonCoding46 = sum(errornonCoding46)
print("sum :\n", hasilnonCoding46)
print(f"\nRow multiplication result:")
print(errornonCoding46)

sum :
 [[36.04061182  7.86647252 13.61803915]
 [ 7.86647252 20.31813393 10.35963868]
 [13.61803915 10.35963868 22.59918918]]

Row multiplication result:
[matrix([[2.88758537, 1.45794589, 3.07552948],
        [1.45794589, 0.73611891, 1.55283913],
        [3.07552948, 1.55283913, 3.27570629]]), matrix([[ 0.15687543, -0.39739512, -0.03478399],
        [-0.39739512,  1.00667693,  0.08811443],
        [-0.03478399,  0.08811443,  0.00771266]]), matrix([[ 2.61912506, -0.68278458, -0.14212815],
        [-0.68278458,  0.17799638,  0.03705165],
        [-0.14212815,  0.03705165,  0.00771266]]), matrix([[ 0.04904511, -0.06124224,  0.11923153],
        [-0.06124224,  0.0764727 , -0.14888347],
        [ 0.11923153, -0.14888347,  0.2898588 ]]), matrix([[0.04904511, 0.19628924, 0.11923153],
        [0.19628924, 0.78559238, 0.4771906 ],
        [0.11923153, 0.4771906 , 0.2898588 ]]), matrix([[ 2.19469620e-03,  6.64363585e-04, -6.27868157e-02],
        [ 6.64363585e-04,  2.01111649e-04, -1.90064000e-02],
        [-6.27868157e-02, -1.90064000e-02,  1.79623231e+00]]), matrix([[0.5554758 , 0.33557911, 0.63461681],
        [0.33557911, 0.20273311, 0.3833905 ],
        [0.63461681, 0.3833905 , 0.72503337]]), matrix([[0.01632419, 0.03533206, 0.09122871],
        [0.03533206, 0.0764727 , 0.19745538],
        [0.09122871, 0.19745538, 0.50983716]]), matrix([[1.38167916, 0.83764169, 1.20734119],
        [0.83764169, 0.50781948, 0.73194946],
        [1.20734119, 0.73194946, 1.0550009 ]]), matrix([[ 0.5554758 ,  0.11890598, -0.18213218],
        [ 0.11890598,  0.02545319, -0.03898749],
        [-0.18213218, -0.03898749,  0.05971841]]), matrix([[ 0.42459209, -0.67226045,  0.26124584],
        [-0.67226045,  1.06439597, -0.41363287],
        [ 0.26124584, -0.41363287,  0.16074108]]), matrix([[ 0.04904511, -0.19000799,  0.25791217],
        [-0.19000799,  0.73611891, -0.99918973],
        [ 0.25791217, -0.99918973,  1.3562756 ]]), matrix([[0.84624584, 1.21651012, 0.35125491],
        [1.21651012, 1.74877891, 0.50494211],
        [0.35125491, 0.50494211, 0.14579689]]), matrix([[ 0.68264121, -0.25191459, -0.05678621],
        [-0.25191459,  0.09296386,  0.02095577],
        [-0.05678621,  0.02095577,  0.00472382]]), matrix([[ 0.04904511, -0.02905081,  0.22324201],
        [-0.02905081,  0.01720762, -0.13223256],
        [ 0.22324201, -0.13223256,  1.01614603]]), matrix([[ 1.82266799, -0.21538969,  0.32991943],
        [-0.21538969,  0.02545319, -0.03898749],
        [ 0.32991943, -0.03898749,  0.05971841]]), matrix([[ 2.61912506, -0.91802968,  0.11123072],
        [-0.91802968,  0.32177864, -0.03898749],
        [ 0.11123072, -0.03898749,  0.00472382]]), matrix([[0.0021947 , 0.04833245, 0.06189242],
        [0.04833245, 1.06439597, 1.3630188 ],
        [0.06189242, 1.3630188 , 1.74542209]]), matrix([[0.0021947 , 0.02790327, 0.02522205],
        [0.02790327, 0.35476095, 0.32067208],
        [0.02522205, 0.32067208, 0.2898588 ]]), matrix([[2.88758537, 0.7169238 , 1.74539542],
        [0.7169238 , 0.17799638, 0.43334321],
        [1.74539542, 0.43334321, 1.0550009 ]]), matrix([[3.21479463, 2.37106834, 0.9653168 ],
        [2.37106834, 1.74877891, 0.71196837],
        [0.9653168 , 0.71196837, 0.2898588 ]]), matrix([[0.84624584, 0.94907358, 1.07132749],
        [0.94907358, 1.06439597, 1.20150501],
        [1.07132749, 1.20150501, 1.3562756 ]]), matrix([[ 0.15687543,  0.17833632, -0.09679024],
        [ 0.17833632,  0.20273311, -0.11003135],
        [-0.09679024, -0.11003135,  0.05971841]]), matrix([[0.68264121, 0.10838186, 0.46059927],
        [0.10838186, 0.01720762, 0.07312861],
        [0.46059927, 0.07312861, 0.31078066]]), matrix([[1.00167023, 1.58609256, 0.55794241],
        [1.58609256, 2.51149484, 0.88347271],
        [0.55794241, 0.88347271, 0.31078066]]), matrix([[ 0.84624584, -0.65554567,  0.35125491],
        [-0.65554567,  0.50781948, -0.27210017],
        [ 0.35125491, -0.27210017,  0.14579689]]), matrix([[ 0.15687543, -0.39739512, -0.34481524],
        [-0.39739512,  1.00667693,  0.87348216],
        [-0.34481524,  0.87348216,  0.75791057]]), matrix([[0.68264121, 0.34857949, 0.71929201],
        [0.34857949, 0.17799638, 0.36729462],
        [0.71929201, 0.36729462, 0.75791057]]), matrix([[0.32568566, 0.75468683, 0.30725048],
        [0.75468683, 1.74877891, 0.71196837],
        [0.30725048, 0.71196837, 0.2898588 ]]), matrix([[ 0.15687543,  0.12076318, -0.09679024],
        [ 0.12076318,  0.09296386, -0.07450942],
        [-0.09679024, -0.07450942,  0.05971841]]), matrix([[ 0.01632419,  0.07247603, -0.00878137],
        [ 0.07247603,  0.32177864, -0.03898749],
        [-0.00878137, -0.03898749,  0.00472382]]), matrix([[6.61702719, 0.3374363 , 1.83673796],
        [0.3374363 , 0.01720762, 0.09366473],
        [1.83673796, 0.09366473, 0.50983716]]), matrix([[ 2.08443539, -0.60911571, -1.03088438],
        [-0.60911571,  0.17799638,  0.30124603],
        [-1.03088438,  0.30124603,  0.50983716]]), matrix([[0.04904511, 0.03533206, 0.29258233],
        [0.03533206, 0.02545319, 0.2107761 ],
        [0.29258233, 0.2107761 , 1.74542209]]), matrix([[ 4.24592095e-01, -9.24069350e-03, -3.50815845e-01],
        [-9.24069350e-03,  2.01111649e-04,  7.63504958e-03],
        [-3.50815845e-01,  7.63504958e-03,  2.89858804e-01]]), matrix([[ 0.01632419, -0.03895586, -0.00878137],
        [-0.03895586,  0.09296386,  0.02095577],
        [-0.00878137,  0.02095577,  0.00472382]]), matrix([[0.01632419, 0.03533206, 0.03122266],
        [0.03533206, 0.0764727 , 0.06757831],
        [0.03122266, 0.06757831, 0.05971841]]), matrix([[0.68264121, 0.70887594, 0.20190653],
        [0.70887594, 0.73611891, 0.20966604],
        [0.20190653, 0.20966604, 0.05971841]]), matrix([[0.09143358, 0.03966553, 0.07389363],
        [0.03966553, 0.01720762, 0.03205638],
        [0.07389363, 0.03205638, 0.05971841]]), matrix([[0.15687543, 0.29348261, 0.39925975],
        [0.29348261, 0.54904737, 0.74693528],
        [0.39925975, 0.74693528, 1.01614603]]), matrix([[0.15687543, 0.06319004, 0.15123475],
        [0.06319004, 0.02545319, 0.06091795],
        [0.15123475, 0.06091795, 0.14579689]])]

In [47]:
error = hasilCoding13 + hasilCoding46 + hasilnonCoding13 + hasilnonCoding46
error = np.round(error, decimals=6)
error

array([[93.449662, 23.112465, 35.338456],
       [23.112465, 66.439542, 30.031428],
       [35.338456, 30.031428, 82.568132]])

In [48]:
he1 = error + factorA
he2 = error + factorB
he3 = error + factorAB
lambda1 = np.round(np.linalg.det(error) / np.linalg.det(he1), decimals=6)
lambda2 = np.round(np.linalg.det(error) / np.linalg.det(he2), decimals=6)
lambda3 = np.round(np.linalg.det(error) / np.linalg.det(he3), decimals=6)
print("Lambda 1:\n",lambda1)
print("\nLambda 2:\n",lambda2)
print("\nLambda 3:\n",lambda3)

Lambda 1:
 0.970307

Lambda 2:
 0.997634

Lambda 3:
 0.986411

In [49]:
F0h1 = np.round(((1-lambda1)/lambda1) * (v2 /v1), decimals=2)
print('\nF0 hipotesis coding dan non coding:')
print(F0h1)
m1 = I - 1 # degrees of freedom factor A

print('\nFtabel :')
print('V1 = ', v1)
print('V2 = ',v2)
Ftabel = stats.f.ppf(0.95, v1, v2)
print(Ftabel)
if  F0h1 > Ftabel:
    print('\nH0 ditolak\nterdapat perbedaan yang signifikan')
else:
    print('\nH0 diterima')

F0 hipotesis coding dan non coding:
4.84

Ftabel :
V1 =  3
V2 =  474
2.6237168336433503

H0 ditolak
terdapat perbedaan yang signifikan

In [50]:
F0h2 = ((1-lambda2)/lambda2) * ((mE + 1 - d)/d)
print('\nF0 hipotesis kelas 1-3 dan 4-6:')
print(F0h2)
m2 = J - 1 # degrees of freedom factor B
v1 = d
v2 = mE + 1 - d
print('\nFtabel :')
print('V1 = ', v1)
print('V2 = ',v2)
Ftabel = stats.f.ppf(0.95, v1, v2)
if  F0h2 >  Ftabel:
    print('\nH0 ditolak\nterdapat perbedaan yang signifikan')
else:
    print('\nH0 diterima')

F0 hipotesis kelas 1-3 dan 4-6:
0.37471457468369834

Ftabel :
V1 =  3
V2 =  474

H0 diterima

In [51]:
F0h3 = ((1-lambda3)/lambda3) * ((mE + 1 - d)/d)
m3 = (I - 1)/ (J - 1) # degrees of freedom factor AxB
print('\nF0 hipotesis coding dan non coding, kelas 1-3 dan 4-6:')
print(F0h3)
v1 = d
v2 = mE + 1 - d
print('\nFtabel :')
print('V1 = ', v1)
print('V2 = ',v2)
Ftabel = stats.f.ppf(0.95, v1, v2)
if  F0h3 > Ftabel:
    print('\nH0 ditolak\nterdapat perbedaan yang signifikan')
else:
    print('\nH0 diterima')

F0 hipotesis coding dan non coding, kelas 1-3 dan 4-6:
2.1766403659326525

Ftabel :
V1 =  3
V2 =  474

H0 diterima

In [52]:
# from statsmodels.multivariate.manova import MANOVA

# # Gabungkan data yang diperlukan
# data = pd.DataFrame({
#     'Science': df['science'],
#     'Technology': df['tech'],
#     'Math': df['math'],
#     'Group': df['group'],  # Coding/Non-Coding
#     'Grade': df['grade']    # 1-3 or 4-6
# })

# # Lakukan MANOVA dan cek hasil Pillai's Trace
# maov = MANOVA.from_formula('Science + Technology + Math ~ Group + Grade', data=data)
# result = maov.mv_test()

# # Cetak hasil MANOVA
# print(result)

In [53]:
# # Periksa nilai p-value untuk Pillai's Trace atau Wilks' Lambda (tergantung yang ingin kamu pakai)
# # Di sini kita periksa berdasarkan Pillai's Trace dari output MANOVA
# # pillai_trace = result['Group']['stat']['Pillai\'s trace']  # Mengambil Pillai's Trace
# p_value_group = result['Group']['stat']['Pr > F']['Pillai\'s trace']  # p-value untuk hipotesis Group (Coding vs Non-Coding)
# p_value_grade = result['Grade']['stat']['Pr > F']['Pillai\'s trace']  # p-value untuk hipotesis Grade (Class 1-3 vs 4-6)
# p_value_intercept = result['Intercept']['stat']['Pr > F']['Pillai\'s trace']

# # Tentukan tingkat signifikansi (alpha)
# alpha = 0.05

# # Uji Hipotesis 1: Coding vs Non-Coding (Group)
# if p_value_group < alpha:
#     print(f"Terdapat perbedaan signifikan antara siswa Coding dan Non-Coding (p-value: {p_value_group}).")
# else:
#     print(f"Tidak ada perbedaan signifikan antara siswa Coding dan Non-Coding (p-value: {p_value_group}).")

# # Uji Hipotesis 2: Kelas 1-3 vs 4-6 (Grade)
# if p_value_grade < alpha:
#     print(f"Terdapat perbedaan signifikan antara kelas 1-3 dan kelas 4-6 (p-value: {p_value_grade}).")
# else:
#     print(f"Tidak ada perbedaan signifikan antara kelas 1-3 dan kelas 4-6 (p-value: {p_value_grade}).")
    
# if p_value_intercept < alpha:
#     print(f"Terdapat perbedaan signifikan antara coding dan noncoding kelas 1-3 dan kelas 4-6 (p-value: {p_value_intercept}).")
# else:
#     print(f"Tidak ada perbedaan signifikan antara coding dan noncoding kelas 1-3 dan kelas 4-6 (p-value: {p_value_intercept}).")

# # Jika ada interaksi yang juga diuji, kamu bisa menambahkannya dengan cara serupa

In [59]:
EH1 =np.linalg.inv(error + factorA) 
pillai1 = np.trace(factorA @ EH1)
print(pillai1)
alpha = 0.05
pillai1_matrix = factorA @ EH1
print("Matriks pillai 1 :", pillai1_matrix)
# Uji Hipotesis 1: Coding vs Non-Coding (Group)
if pillai1 < alpha:
    print(f"Terdapat perbedaan signifikan antara siswa Coding dan Non-Coding ")
else:
    print(f"Tidak ada perbedaan signifikan antara siswa Coding dan Non-Coding")

0.029692806790146842
Matriks pillai 1 : [[0.00342695 0.01438222 0.00489999]
 [0.00490465 0.02058388 0.00701288]
 [0.00397385 0.01667747 0.00568198]]
Terdapat perbedaan signifikan antara siswa Coding dan Non-Coding

In [63]:
EH2 =np.linalg.inv(error + factorB) 
pillai2 = np.trace(factorB @ EH2)
print(pillai2)
pillai2_matrix = np.round(factorB @ EH2, decimals=4)
print("Matriks pillai 2 :", pillai2_matrix)

0.002366456214629906
Matriks pillai 2 : [[-0.     -0.0001  0.001 ]
 [-0.     -0.0001  0.0007]
 [-0.0001 -0.0003  0.0025]]

In [62]:
EH3 =np.linalg.inv(error + factorAB) 
pillai3 = np.round(np.trace(factorAB @ EH3), decimals=4)
print(pillai3)
pillai3_matrix = factorAB @ EH3
print("Matriks pillai 3 :", pillai3_matrix)

0.0136
Matriks pillai 3 : [[ 0.00218792 -0.00120189  0.00301152]
 [-0.00092686  0.00459748  0.00117467]
 [ 0.00057141 -0.00025361  0.00685775]]

In [ ]:
from scipy.stats import pearsonr
correlation = coding_df['tech'].corr(coding_df['math'])
print(f"Korelasi Pearson menggunakan pandas: {correlation}")

# Menghitung korelasi Pearson menggunakan scipy
correlation, p_value = pearsonr(coding_df['tech'], coding_df['math'])
# print(f"Korelasi Pearson menggunakan scipy: {correlation}, p-value: {p_value}")

Korelasi Pearson menggunakan pandas: 0.34424272700735215

In [ ]:
from math import sqrt
X = sum(coding_df['tech'])
Y = sum(coding_df['math'])
X2 = sum([x**2 for x in coding_df['tech']])
Y2 = sum([y**2 for y in coding_df['math']])
XY = sum([x * y for x, y in zip(coding_df['tech'], coding_df['math'])])
n = len(coding_df['tech'])
r = ( (n * XY) - (X * Y) ) / ( sqrt( ((n * X2) - X**2 ) * ((n *Y2) - Y**2)) )
print("X =",X)
print("Y =",Y)
print("X^2 =",X2)
print("Y^2 =",Y2)
print("XY =",XY)
print("r =",r)

X = 5282
Y = 5141
X^2 = 466752
Y^2 = 442597
XY = 453241
r = 0.3442427270073518

In [ ]:
from math import sqrt
X = sum(coding_df['tech'])
Y = sum(coding_df['science'])
X2 = sum([x**2 for x in coding_df['tech']])
Y2 = sum([y**2 for y in coding_df['science']])
XY = sum([x * y for x, y in zip(coding_df['tech'], coding_df['science'])])
n = len(coding_df['tech'])
r = ( (n * XY) - (X * Y) ) / ( sqrt( ((n * X2) - X**2 ) * ((n *Y2) - Y**2)) )
print("X =",X)
print("Y =",Y)
print("X^2 =",X2)
print("Y^2 =",Y2)
print("XY =",XY)
print("r =",r)

X = 5282
Y = 5137
X^2 = 466752
Y^2 = 441231
XY = 452736
r = 0.3220359471947712

In [68]:
V1 = np.linalg.inv(factorA + error) @ factorA
V1

array([[0.00342695, 0.00490465, 0.00397385],
       [0.01438222, 0.02058388, 0.01667747],
       [0.00489999, 0.00701288, 0.00568198]])